import { useState } from "react";
import { Link, useLocation } from "wouter";
import { ShieldCheck, ArrowLeft, LogOut } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";

export default function AdminPassword() {
  const { user, loading, logout } = useAuth();
  const [, navigate] = useLocation();
  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [pending, setPending] = useState(false);
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#f4faf7] text-sm text-[#6d918a]">กำลังตรวจสอบสิทธิ์...</div>;
  if (!user || user.role !== "admin") return <div className="grid min-h-screen place-items-center bg-[#f4faf7] p-5"><div className="rounded-3xl bg-white p-8 text-center shadow-xl"><p className="font-semibold text-[#315f58]">หน้านี้สำหรับผู้ดูแลระบบเท่านั้น</p><Link href="/dashboard" className="mt-4 inline-block text-sm text-[#238f76]">กลับ Dashboard</Link></div></div>;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (newPassword.length < 10) return toast.error("รหัสผ่านใหม่ต้องมีอย่างน้อย 10 ตัวอักษร"); if (newPassword !== confirmPassword) return toast.error("รหัสผ่านใหม่และการยืนยันรหัสผ่านไม่ตรงกัน"); setPending(true); try { const response = await fetch("/api/admin/password", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentPassword, newPassword, confirmPassword }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || "ไม่สามารถเปลี่ยนรหัสผ่านได้"); toast.success("เปลี่ยนรหัสผ่านสำเร็จ กรุณาเข้าสู่ระบบใหม่"); setTimeout(() => navigate("/dashboard"), 500); } catch (error) { toast.error(error instanceof Error ? error.message : "ไม่สามารถเปลี่ยนรหัสผ่านได้"); setPending(false); } };
  return <div className="min-h-screen bg-[#f4faf7] p-5 lg:p-10"><div className="mx-auto max-w-xl"><div className="mb-5 flex items-center justify-between"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm text-[#56847a] hover:text-[#238f76]"><ArrowLeft className="size-4" />กลับ Dashboard</Link><Button variant="outline" size="sm" onClick={logout} className="rounded-xl border-[#f2d5ce] text-[#b44b3e]"><LogOut className="mr-1.5 size-3.5" />ออกจากระบบ</Button></div><section className="rounded-[2rem] border border-[#d2ebe5] bg-white p-7 shadow-[0_18px_60px_rgba(36,91,81,.10)] sm:p-9"><div className="flex items-start gap-3"><div className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#e4f7f1] text-[#1c8c72]"><ShieldCheck className="size-6" /></div><div><h1 className="font-display text-2xl font-bold text-[#1a3d36]">เปลี่ยนรหัสผ่านผู้ดูแลระบบ</h1><p className="mt-1 text-xs text-[#6b9189]">เปลี่ยนรหัสผ่านจากระบบโดยตรง ไม่ต้องแก้ Environment Variables</p></div></div><form onSubmit={submit} className="mt-7 space-y-4"><div><label className="text-xs font-semibold text-[#284f47]">รหัสผ่านปัจจุบัน</label><Input type="password" autoComplete="current-password" value={currentPassword} onChange={e => setCurrentPassword(e.target.value)} disabled={pending} className="mt-1.5 h-11 rounded-xl" /></div><div><label className="text-xs font-semibold text-[#284f47]">รหัสผ่านใหม่</label><Input type="password" autoComplete="new-password" value={newPassword} onChange={e => setNewPassword(e.target.value)} disabled={pending} className="mt-1.5 h-11 rounded-xl" /><p className="mt-1.5 text-[11px] text-[#7a9a93]">อย่างน้อย 10 ตัวอักษร</p></div><div><label className="text-xs font-semibold text-[#284f47]">ยืนยันรหัสผ่านใหม่</label><Input type="password" autoComplete="new-password" value={confirmPassword} onChange={e => setConfirmPassword(e.target.value)} disabled={pending} className="mt-1.5 h-11 rounded-xl" /></div><Button type="submit" disabled={pending || !currentPassword || !newPassword || !confirmPassword} className="h-11 w-full rounded-xl bg-[#238f76] font-semibold text-white hover:bg-[#187863]">{pending ? "กำลังเปลี่ยนรหัสผ่าน..." : "เปลี่ยนรหัสผ่าน"}</Button></form><div className="mt-5 rounded-xl border border-[#e4f5ef] bg-[#f5fbf9] p-3 text-[11px] leading-5 text-[#5e877f]">หลังเปลี่ยนรหัสผ่าน ระบบจะออกจากเซสชันปัจจุบันและให้เข้าสู่ระบบใหม่ เพื่อความปลอดภัย</div></section></div></div>;
}
