import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { ArrowRight, BellRing, Bot, CalendarDays, CheckCircle2, FileArchive, FolderSearch, HeartHandshake, ReceiptText, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { Link } from "wouter";

const features = [
  { icon: BellRing, tone: "bg-[#dff8e9] text-[#168b6f]", title: "เตือนเหมือนคุยกับเพื่อน", detail: "บอกวัน เวลา หรือความถี่ตามธรรมชาติ ไมโลแปลงเป็นการเตือนให้ทันที" },
  { icon: FileArchive, tone: "bg-[#e4f6ff] text-[#2785ad]", title: "เก็บไว้ ไม่มีวันหาย", detail: "ข้อความ ลิงก์ รูป และไฟล์ถูกจัดเก็บ พร้อมค้นหาจากแชทได้" },
  { icon: UsersRound, tone: "bg-[#fff0d8] text-[#b56b25]", title: "ผู้ช่วยประจำกลุ่ม", detail: "ชวนไมโลเข้ากลุ่ม ให้ช่วยเตือนและเก็บข้อมูลของกลุ่ม" },
  { icon: ReceiptText, tone: "bg-[#f2e9ff] text-[#8060b6]", title: "รายรับรายจ่ายจากแชท", detail: "พิมพ์รายการและตั้งงบประมาณได้ในประโยคเดียว" },
];

const faq = [
  ["ไมโลตั้งเตือนได้แบบใดบ้าง?", "ตั้งเตือนครั้งเดียว รายวัน รายสัปดาห์ รายเดือน และทุกจำนวนเวลาที่กำหนดได้ เพียงพิมพ์ภาษาธรรมชาติใน LINE"],
  ["ไฟล์ที่ส่งให้ไมโลอยู่ที่ไหน?", "ระบบเก็บไฟล์จริงไว้ในคลัง และบันทึกข้อมูลกำกับเพื่อให้ค้นหาได้จากแชทหรือหน้าแดชบอร์ดหลังเชื่อมบัญชี"],
  ["ใช้ในกลุ่ม LINE ได้หรือไม่?", "ได้ เพิ่มไมโลเข้ากลุ่ม แล้ว mention หรือพิมพ์เรียกชื่อไมโลก่อนสั่งงาน เพื่อแยกคำสั่งออกจากบทสนทนาปกติ"],
  ["ส่งภาพใบนัดหรือใบเสร็จได้หรือไม่?", "ได้ ไมโลจะอ่านข้อมูลที่เห็นได้ในภาพ แล้วเสนอรายการเตือนหรือรายรับรายจ่ายให้ตรวจสอบ"],
];

export default function Home() {
  return (
    <div className="min-h-screen overflow-hidden bg-[#f8fffd] text-[#245851]">
      <header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 lg:px-8">
        <Link href="/" className="flex items-center gap-2.5"><span className="grid size-10 place-items-center rounded-2xl bg-[#2bb895] text-white soft-shadow"><Bot className="size-5" /></span><span className="font-display text-xl font-semibold">ไมโล</span></Link>
        <nav className="hidden items-center gap-7 text-sm font-medium text-[#4a7a73] md:flex"><a href="#features">ความสามารถ</a><a href="#groups">สำหรับกลุ่ม</a><a href="#faq">คำถามที่พบบ่อย</a></nav>
        <Link href="/dashboard"><Button className="rounded-full bg-[#238f76] px-5 text-white hover:bg-[#157a62]">เข้าสู่ไมโล <ArrowRight className="ml-1 size-4" /></Button></Link>
      </header>
      <main>
        <section className="relative mx-auto grid max-w-6xl items-center gap-12 px-5 pb-20 pt-10 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:pb-28 lg:pt-20">
          <div className="hero-orb absolute -left-40 top-4 size-[620px]" />
          <div className="relative z-10"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#beeadd] bg-white/85 px-4 py-2 text-sm font-medium text-[#287d6b] shadow-sm"><Sparkles className="size-4" />ผู้ช่วยส่วนตัวใน LINE ของคุณ</div><h1 className="font-display max-w-2xl text-5xl font-semibold leading-[1.14] tracking-tight text-[#245851] sm:text-6xl">ชีวิตจัดการง่าย<br />แค่คุยกับ <span className="text-[#1ea585]">ไมโล</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#56807a]">เตือน เก็บไฟล์ จดรายรับรายจ่าย และช่วยงานกลุ่มได้ในแชท LINE เดียว โดยไม่ต้องสลับหลายแอป</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/dashboard"><Button size="lg" className="rounded-full bg-[#238f76] px-7 text-base text-white hover:bg-[#157a62]">เชื่อมต่อ LINE ของคุณ <ArrowRight className="ml-2 size-4" /></Button></Link><a href="#features"><Button size="lg" variant="outline" className="rounded-full border-[#b8ded4] bg-white px-7 text-base text-[#357269] hover:bg-[#effbf7]">ดูความสามารถ</Button></a></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-3 text-sm text-[#5d827c]"><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#20a586]" />ภาษาไทยธรรมชาติ</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#20a586]" />ใช้กับกลุ่ม LINE ได้</span><span className="flex items-center gap-2"><ShieldCheck className="size-4 text-[#20a586]" />เก็บข้อมูลอย่างเป็นระบบ</span></div></div>
          <div className="relative mx-auto w-full max-w-[380px]"><div className="floaty paper-shadow overflow-hidden rounded-[2.2rem] border-[7px] border-white bg-[#edf9fb] p-3"><div className="mb-3 flex items-center justify-between px-1"><span className="text-xs font-semibold text-[#7da59e]">23:45</span><span className="rounded-full bg-white px-3 py-1 text-xs font-medium text-[#2b8c77]">ไมโล</span></div><div className="space-y-3 rounded-[1.7rem] bg-[#d7eff4] px-3 py-5"><div className="flex items-end gap-2"><div className="grid size-8 shrink-0 place-items-center rounded-full bg-[#2bb895] text-white"><Bot className="size-4" /></div><div className="max-w-[82%] rounded-2xl rounded-bl-md bg-white px-4 py-3 text-sm leading-6 text-[#356b64] shadow-sm">สวัสดีครับ ผมไมโล มีอะไรให้ช่วยจัดการไหมครับ?</div></div><div className="ml-auto w-fit max-w-[78%] rounded-2xl rounded-br-md bg-[#9eeacb] px-4 py-3 text-sm text-[#225c50] shadow-sm">เตือนประชุมทีมพรุ่งนี้ 10 โมง</div><div className="flex items-end gap-2"><div className="grid size-8 shrink-0 place-items-center rounded-full bg-[#2bb895] text-white"><Bot className="size-4" /></div><div className="max-w-[82%] rounded-2xl rounded-bl-md bg-white px-4 py-3 text-sm leading-6 text-[#356b64] shadow-sm"><b className="text-[#168b6f]">ตั้งเตือนแล้ว</b><br />ประชุมทีม<br /><span className="text-xs text-[#79a39c]">พรุ่งนี้ 10:00 น.</span></div></div><div className="ml-auto w-fit max-w-[78%] rounded-2xl rounded-br-md bg-[#9eeacb] px-4 py-3 text-sm text-[#225c50]">จ่ายกาแฟ 65 บาท</div><div className="flex items-end gap-2"><div className="grid size-8 shrink-0 place-items-center rounded-full bg-[#2bb895] text-white"><Bot className="size-4" /></div><div className="max-w-[82%] rounded-2xl rounded-bl-md bg-white px-4 py-3 text-sm leading-6 text-[#356b64]">บันทึกรายจ่าย <b>65 บาท</b><br /><span className="text-xs text-[#79a39c]">หมวดอาหาร</span></div></div></div><div className="mt-3 flex items-center gap-2 rounded-2xl bg-white px-3 py-2 text-xs text-[#9ab6b1]"><span className="rounded-lg bg-[#edf9f6] px-2 py-1 text-[#2a9278]">เมนู</span><span>พิมพ์สิ่งที่อยากจัดการ...</span></div></div><div className="floaty-late absolute -bottom-5 -left-9 rounded-2xl border border-[#ccebe3] bg-white p-3 paper-shadow"><div className="flex items-center gap-2"><span className="grid size-9 place-items-center rounded-xl bg-[#dff8e9] text-[#168b6f]"><BellRing className="size-4" /></span><div><p className="text-xs font-semibold">เตือนตรงเวลา</p><p className="text-[10px] text-[#78a09a]">ทุกสิ่งเป็นระบบ</p></div></div></div></div>
        </section>
        <section id="features" className="mint-grid border-y border-[#d9f0e9] bg-[#effbf7] py-20"><div className="mx-auto max-w-6xl px-5 lg:px-8"><p className="text-sm font-semibold text-[#1e9a7d]">หนึ่งแชท ครบทุกการจัดการ</p><h2 className="font-display mt-3 text-4xl font-semibold leading-tight text-[#245851]">ไมโลจำสิ่งสำคัญ<br />เพื่อให้คุณไม่ต้องจำทุกอย่างเอง</h2><div className="mt-11 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{features.map(item => <article key={item.title} className="dashed-tape rounded-[1.6rem] bg-white p-6 paper-shadow"><span className={`grid size-12 place-items-center rounded-2xl ${item.tone}`}><item.icon className="size-6" /></span><h3 className="font-display mt-6 text-xl font-semibold text-[#2b5c55]">{item.title}</h3><p className="mt-3 text-sm leading-6 text-[#688b85]">{item.detail}</p></article>)}</div></div></section>
        <section id="groups" className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-24 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div className="rounded-[2rem] border border-[#d7eee9] bg-[#f1fbf9] p-6 paper-shadow"><div className="flex items-center gap-3 border-b border-[#d8eeea] pb-5"><div className="grid size-11 place-items-center rounded-2xl bg-[#2bb895] text-white"><UsersRound className="size-5" /></div><div><p className="font-semibold">ทีมวันพุธ</p><p className="text-xs text-[#7e9f99]">ไมโลอยู่ในกลุ่มแล้ว</p></div></div><div className="mt-5 space-y-3"><div className="w-[78%] rounded-2xl rounded-tl-md bg-white p-3 text-sm text-[#547a74] shadow-sm">@ไมโล เตือนส่งรายงานทุกวันศุกร์ 16:00 ด้วย</div><div className="ml-auto w-[76%] rounded-2xl rounded-tr-md bg-[#c8f1dc] p-3 text-sm text-[#356c61]">ตั้งเตือนสำหรับกลุ่มแล้วครับ</div><div className="w-[85%] rounded-2xl rounded-tl-md bg-white p-3 text-sm text-[#547a74] shadow-sm">ส่งไฟล์นี้ไว้ก่อนนะ</div><div className="ml-auto w-[78%] rounded-2xl rounded-tr-md bg-[#c8f1dc] p-3 text-sm text-[#356c61]">เก็บเข้าแฟ้มของกลุ่มให้แล้ว</div></div></div><div><p className="text-sm font-semibold text-[#1e9a7d]">ไมโลในทุกกลุ่มที่คุณใช้งาน</p><h2 className="font-display mt-3 text-4xl font-semibold leading-tight text-[#245851]">ไม่ต้องตามงานในแชท<br />ให้ไมโลช่วยจำแทน</h2><p className="mt-5 max-w-xl text-lg leading-8 text-[#668b84]">เพิ่มไมโลเข้ากลุ่ม แล้ว mention เพื่อสั่งงาน ไมโลจะแยกคลังและการเตือนตามแต่ละกลุ่มอย่างเป็นระเบียบ</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-[#d5ece6] bg-white p-4"><CalendarDays className="size-5 text-[#1d9a7c]" /><p className="mt-3 text-sm font-semibold">เตือนตามกลุ่ม</p><p className="mt-1 text-xs leading-5 text-[#759791]">ส่งกลับไปยังแชทเดิม</p></div><div className="rounded-2xl border border-[#d5ece6] bg-white p-4"><FolderSearch className="size-5 text-[#2785ad]" /><p className="mt-3 text-sm font-semibold">คลังของกลุ่ม</p><p className="mt-1 text-xs leading-5 text-[#759791]">ค้นหาไฟล์และข้อความได้ทันที</p></div></div></div></section>
        <section id="faq" className="border-t border-[#dcefe9] bg-[#f5fcfa] py-20"><div className="mx-auto grid max-w-5xl gap-10 px-5 lg:grid-cols-[.75fr_1.25fr] lg:px-8"><div><p className="text-sm font-semibold text-[#1e9a7d]">คำถามที่พบบ่อย</p><h2 className="font-display mt-3 text-4xl font-semibold leading-tight text-[#245851]">สงสัยเรื่องไมโล<br />เราตอบไว้ให้แล้ว</h2><div className="mt-6 flex items-center gap-3 rounded-2xl border border-[#cde8e0] bg-white p-4 text-sm text-[#638881]"><HeartHandshake className="size-5 shrink-0 text-[#e391a7]" />ไมโลช่วยจัดการสิ่งที่ค้างอยู่ในใจคุณ</div></div><Accordion type="single" collapsible className="rounded-3xl border border-[#d5ece6] bg-white px-5 paper-shadow">{faq.map(([question, answer], index) => <AccordionItem key={question} value={`item-${index}`} className="border-[#e1f0ec]"><AccordionTrigger className="py-5 text-left font-display text-base font-medium text-[#2b5d56] hover:no-underline">{question}</AccordionTrigger><AccordionContent className="pb-5 text-sm leading-7 text-[#708f89]">{answer}</AccordionContent></AccordionItem>)}</Accordion></div></section>
        <section className="mx-auto max-w-6xl px-5 py-20 lg:px-8"><div className="relative overflow-hidden rounded-[2.4rem] bg-[#226e61] px-7 py-12 text-center text-white"><div className="absolute inset-0 opacity-20 mint-grid" /><div className="relative"><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-white/15"><Sparkles className="size-6" /></span><h2 className="font-display mt-5 text-4xl font-semibold">เริ่มให้ไมโลช่วยดูแลวันของคุณ</h2><p className="mx-auto mt-4 max-w-2xl text-[#d2f6ee]">เข้าหน้าแดชบอร์ดเพื่อลงชื่อเข้าใช้ เชื่อมบัญชี LINE และจัดการทุกอย่างจากที่เดียว</p><Link href="/dashboard"><Button size="lg" className="mt-7 rounded-full bg-white px-8 text-[#16725f] hover:bg-[#dcf7ef]">เริ่มเชื่อมต่อไมโล <ArrowRight className="ml-2 size-4" /></Button></Link></div></div></section>
      </main>
      <footer className="border-t border-[#dcefe9] px-5 py-8 text-center text-sm text-[#7b9c96]">ไมโล — ผู้ช่วยส่วนตัวและผู้ช่วยประจำกลุ่มใน LINE</footer>
    </div>
  );
}
